
server:
    port: ${SERVER_PORT}
spring:
    servlet:
      multipart:
        max-file-size: 3MB
        max-request-size: 3MB

    config:
      import:
         - env.properties
    application:
        name: zeballos_application
    datasource:
        url: ${DB_URL}
        username: ${DB_USER}
        password: ${DB_PASS}
        #driver-class-name: com.mysql.cj.jdbc.Driver
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                #dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                #dialect: org.hibernate.dialect.PostgreSQLDialect
                show_sql: true
app:
    jwt:
        secret: ${JWT_SECRET}
        expiration: ${JWT_EXPIRATION}