
server:
    port: ${SERVER_PORT}
spring:
    application:
        name: zeballos_application
    config:


    datasource:
        url: ${DB_URL}
        username: ${DB_USER}
        password: ${DB_PASS}
        driver-class-name: org.postgresql.Driver #com.mysql.cj.jdbc.Driver


    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
            ddl-auto: update
        show-sql: true

app:
    jwt:
        secret: ${JWT_SECRET}
        expiration: ${JWT_EXPIRATION}


